-- CreateTable
CREATE TABLE "Functionpoint" (
    "fpID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EI" TEXT NOT NULL,
    "EO" TEXT NOT NULL,
    "EQ" TEXT NOT NULL,
    "ILF" TEXT NOT NULL,
    "ELF" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CAF" (
    "cafID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DC" INTEGER NOT NULL,
    "DP" INTEGER NOT NULL,
    "DS" INTEGER NOT NULL,
    "P" INTEGER NOT NULL,
    "S" INTEGER NOT NULL,
    "UI" INTEGER NOT NULL,
    "R" INTEGER NOT NULL,
    "EoI" INTEGER NOT NULL,
    "OE" INTEGER NOT NULL,
    "ODS" INTEGER NOT NULL,
    "OTV" INTEGER NOT NULL,
    "CU" INTEGER NOT NULL,
    "ISPF" INTEGER NOT NULL,
    "ICC" INTEGER NOT NULL
);
